site_name: Trombone 
pages: 
- ['index.md',          'Docs', 'Contents']
- ['introduction.md',   'Docs', 'Introduction']
- ['install.md',        'Docs', 'Installation']
- ['configuration.md',  'Docs', 'Basic Configuration']
- ['format.md',         'Docs', 'Route Format']
- ['dry-block.md',      'Docs', 'DRY-block Notation']
- ['non-sql.md',        'Docs', 'Non-SQL Routes']
- ['authentication.md', 'Docs', 'Authentication']
- ['pipelines.md',      'Docs', 'Pipelines']
- ['array.md',          'Docs', 'Array Actions']
- ['wildcard.md',       'Docs', 'Wildcard Operators']
- ['response.md',       'Docs', 'Response Codes']
- ['command-line.md',   'Docs', 'Command Line Flags']
- ['rest.md',           'Docs', 'REST Conventions']
- ['bnf.md',            'Docs', 'BNF Grammar']
- ['middleware.md',     'Docs', 'Middleware']
- ['examples.md',       'Docs', 'Examples']
- ['about.md',          'About']
theme: readthedocs
